import '@/styles/globals.css'
import React from 'react';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import Head from 'next/head'

export default function App({ Component, pageProps }) {
  return (
    <UserProvider>
      <Head>
        <title>Workout Logger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
      <footer className="m-4 dark:bg-gray-800">
        <span className="flex justify-center text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a href="" className="hover:underline">Neoathletics™</a>. All Rights Reserved.</span>
      </footer>
    </UserProvider>
  );
}
